In [1]:
# why python?
#simple syntax
#High level language (Human understandable language)
#Length of code is very small
#Open source (free to download and if we are capable of modifying the python language we do it)
#High level interpreter(memory management can done by itself)
#object oriented and procedure oriented language
#standard libraries(200+)


In [2]:
import numpy as np

In [3]:
print("hello")

hello


In [4]:
print(5**2) #exponent

25


In [5]:
1+1  #addition

2

In [6]:
4/2 #divison (here we get the float number as an output)

2.0

In [7]:
4//2 

2

In [8]:
name="ganesh"
num=9182649015

In [9]:
print("my number is {} and my name is {}".format (num,name))

my number is 9182649015 and my name is ganesh


In [10]:
"my number is {} and my name is {}".format (num,name)

'my number is 9182649015 and my name is ganesh'

In [11]:
"my number is {one} and my name is {two},{three}".format (one=num,two=name,three=num)

'my number is 9182649015 and my name is ganesh,9182649015'

In [12]:
O="hello hyderabad"
O[0]

'h'

In [13]:
O[:5]

'hello'

In [14]:
O[:]

'hello hyderabad'

In [15]:
O[0:]

'hello hyderabad'

In [16]:
my_book=["a","b","c"]
my_book.append("d")

In [17]:
print(my_book)

['a', 'b', 'c', 'd']


In [18]:
my_book[0]

'a'

In [19]:
my_book[0:]

['a', 'b', 'c', 'd']

In [20]:
my_book[1]

'b'

In [21]:
my_book[2]

'c'

In [22]:
my_book[0]="hey myannn"

In [23]:
my_book

['hey myannn', 'b', 'c', 'd']

In [24]:
book= [1,2,3,[1,2]]

In [25]:
print(book)

[1, 2, 3, [1, 2]]


In [26]:
book[0]

1

In [27]:
book[3]

[1, 2]

In [28]:
book[3][0]

1

In [29]:
a=1

In [30]:
print(type(a))

<class 'int'>


In [31]:
print(float(a))

1.0


# Dictionary

In [32]:
a={'key1':'a', 'key2':'b'}

In [33]:
a["key1"]

'a'

In [34]:
a['key2']

'b'

# Boolean

In [35]:
True

True

In [36]:
print(type(True))

<class 'bool'>


In [37]:
False

False

In [38]:
print(type(False))

<class 'bool'>


# Numerical Python (Numpy)

In [39]:
import numpy

# #Here, kesler library was not found inbuilt in the jupyter notebook

In [40]:
import kesler

ModuleNotFoundError: No module named 'kesler'

In [ ]:
import matplotlib

In [ ]:
import pandas

In [41]:
import django

ModuleNotFoundError: No module named 'django'

# Numpy Arrays

In [42]:
list=[1,2,3,4,5,6]

In [54]:
print(list)

[1, 2, 3, 4, 5, 6]


In [55]:
np.array(list)

array([1, 2, 3, 4, 5, 6])

In [44]:
import numpy as np

In [45]:
np.array(list)

array([1, 2, 3, 4, 5, 6])

In [46]:
import numpy as nb

In [47]:
nb.array

<function numpy.array>

# [] indicates one dimensional array

In [52]:
list=[1,2,3,4,5,6]

In [60]:
nb.array(list)

array([1, 2, 3, 4, 5, 6])

In [62]:
array1=[1,2.5,"a",0.5]

In [63]:
np.array(array1)

array(['1', '2.5', 'a', '0.5'], dtype='<U32')

In [64]:
"""Observe that since there is a string value in the list, all integer and float values have been promoted to string, while converting the list to array."""

'Observe that since there is a string value in the list, all integer and float values have been promoted to string, while converting the list to array.'

In [18]:
import numpy as np

# To find the numpy version we are using

In [17]:
print(np.__version__)

1.24.3


# [[]] indicates two dimensional array

In [67]:
my_list=[[1,2,3],[4,5,6],[7,8,9]]

In [68]:
print(my_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [69]:
np.array

<function numpy.array>

In [70]:
np.array(my_list) #two dimensional array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# np.arange() this is similar to range() in python

In [30]:
np.arange(0,10) #we get number from 0 to 9 but if we wanted to get 0 to 10 we need mention(0,11)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0,21,2) #here 2 indicates to print the even numbers between 0 to 21

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [32]:
np.zeros(2)

array([0., 0.])

In [33]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.zeros(int(2))

array([0., 0.])

In [35]:
np.ones(3) #one dimesnsional

array([1., 1., 1.])

In [37]:
np.ones((3,2)) #two dimensional

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# linspace
Returns evenly spaced numbers over a specified interval

In [38]:
np.linspace(0,15,3)

array([ 0. ,  7.5, 15. ])

In [39]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

# zero dimension

In [8]:
a=np.array(1)

In [41]:
a

array(1)

In [42]:
b=np.array([1,2,3,4,5]) #coma separated are list

In [44]:
print(b)     #space separated are arrays

[1 2 3 4 5]


In [49]:
c=np.array([[1,2,3],[2,3,4],[3,4,5]])

In [50]:
print(c)            #two dimensional array

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [54]:
c[0][0]   #indexing

1

In [56]:
d=np.array([1,2,3,4,5,6,7,8,9,0])

In [57]:
print(d)

[1 2 3 4 5 6 7 8 9 0]


In [59]:
print(d[0:])   #slicing

[1 2 3 4 5 6 7 8 9 0]


# Three dimensional array is nothing but collection of two dimensional array....

In [6]:
import numpy as np

In [7]:
k=np.array([[[10,2,3],[4,5,6]],[[109,2,3],[1,2,3]]]) #"three square brackets signifies that its a three dimensional array"

In [8]:
print(k)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [1 2 3]]]


In [10]:
k[1][1][0]

1

# np.asarray()

In [11]:
c=[1,2,3,4,5]
d=np.asarray(c,dtype=float)

In [12]:
print(d)

[1. 2. 3. 4. 5.]


In [15]:
# asarray with nditer()

In [18]:
f=[[1,2],[2,3]]

In [19]:
g=np.asarray(f,dtype=float)

In [20]:
print(g)

[[1. 2.]
 [2. 3.]]


In [38]:
import numpy as np

# Methods for creating an array:

### 0-dimensional array

In [9]:
a=np.array(1)    #zero dimensional array

In [10]:
a

array(1)

In [23]:
print(np.array(a))

1


### 1-dimensional array

In [12]:
b=[1,2,3,4]   #list are comma separated values     #1-dimensional array

In [13]:
np.array(b)

array([1, 2, 3, 4])

In [20]:
print(np.array(b))  #array are space separated values

[1 2 3 4]


### accessing the values using index

In [24]:
b[0]

1

### 2-dimensional array

In [25]:
c=[[1,2,3,4],[5,6,7,8]]    #2-dimensional array: collection two 1-dimensional array

In [16]:
print(np.array(c))        #two square brackets defines it as a 2-dimensional array

[[1 2 3 4]
 [5 6 7 8]]


### accessing the values using index 

In [18]:
c[0][1]    # by this also we can get to know that it is a 2-dimensional array

2

### 3-dimensional array

In [27]:
d=[[[1,2,3],[4,5,6],[7,8,9]]]    # three square brackets represents 3-dimensional array

In [28]:
print(np.array(d))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


### accessing the values using index

In [32]:
d[0][0][1]   #by this also we can get to know that it is a 3-dimensional array

2

### Another type of 3-dimensional array

In [33]:
f=[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]    # collection of two 2-dimensional array is called 3-dimensional array

In [34]:
f[0][0][1]     #accessing the values using index method

2

### asarray()

In [39]:
e=[1,2,4,5]   #1-dimensional array

In [40]:
f=np.asarray(e,dtype=str)      #"e" is the input, "dtype" means data type

In [41]:
print(np.array(f))

['1' '2' '4' '5']


### asarray with nditer()

In [47]:
c=[[1,2,3],[4,5,6]]

In [49]:
d=np.asarray(c,dtype=float,order="C")       #order="C" represents row major order

In [50]:
print(np.array(d))

[[1. 2. 3.]
 [4. 5. 6.]]


In [52]:
for i in np.nditer(d):
    print(i)                           #now we can clearly see the row major order which we have given earlier

1.0
2.0
3.0
4.0
5.0
6.0


In [53]:
a=[[1,2,3],[4,5,6]]

In [55]:
b=np.asarray(a,dtype=str,order="F")    #order="F" represents column major order

In [59]:
for i in np.nditer(b):
    print(i)

1
4
2
5
3
6


### frombuffer()

In [60]:
a=b"Hello Floks!"       #"b" represents buffer.

In [62]:
np.frombuffer(a,dtype="S1")   #"S1" represents string

array([b'H', b'e', b'l', b'l', b'o', b' ', b'F', b'l', b'o', b'k', b's',
       b'!'], dtype='|S1')

In [63]:
np.frombuffer(a,dtype="S1",count=5)     #"count" represents the no. of elements needed to be printed.

array([b'H', b'e', b'l', b'l', b'o'], dtype='|S1')

In [64]:
np.frombuffer(a,dtype="S1",offset=6)     #"offset" represents the start point of the elements to be printed"

array([b'F', b'l', b'o', b'k', b's', b'!'], dtype='|S1')

### fromiter()

In [69]:
a=[1,2,3,4,5,6,7,8,9,0]

In [73]:
np.fromiter(a,dtype=int,count=8)

array([1, 2, 3, 4, 5, 6, 7, 8])

# Initializing Array/Assigning values to an array

### zeros()

In [76]:
a=np.zeros(3)     #1-dimensional array with 3 elements(zeros)

In [77]:
print(a)

[0. 0. 0.]


In [80]:
b=np.zeros([2,3])

In [81]:
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


### ones()

In [84]:
a=np.ones(3)    #1-dimensional array with three elements(ones)

In [83]:
print(a)

[1. 1. 1.]


### full()

In [85]:
a=np.full([2,3],4)    #[2,3],4 represents 2-dimensional array() filled with 4 as an element (2-rows)   (3-columns)

In [86]:
print(a)

[[4 4 4]
 [4 4 4]]


In [87]:
b=np.full([2,3,4],5)

In [88]:
print(b)

[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


### random.rand()

In [97]:
a=np.random.rand(2,3)    #random values

In [30]:
print(a)

[10 12 14 16 18]


In [7]:
import numpy as np

### eye()

In [99]:
#Diagonal elements will be filled with one's and remaining will be filled with zero's

In [10]:
np.eye(2)  #2*2 matrix

array([[1., 0.],
       [0., 1.]])

In [11]:
np.eye(3) #3*3 matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(4)  #4*4 matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Numerical Range

### arange()

In [13]:
a=np.arange(10,20,2)   #1-dimensional array using arange()

In [14]:
a

array([10, 12, 14, 16, 18])

In [19]:
print(a)

[10 12 14 16 18]


In [16]:
#even we can change the datatype withing the arange() function

In [17]:
b=np.arange(10,100,20,dtype=float)       #20 represents difference

In [18]:
print(b)

[10. 30. 50. 70. 90.]


In [25]:
b=np.arange(0,11,2)

In [28]:
print(b)    #6 elements (evenly distributed elements)

[ 0  2  4  6  8 10]


### reshape()

In [27]:
b.reshape(2,3)   #to change the dimension we use reshape() function but it will work only for the evenly distributed elements.

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [31]:
b.reshape(1,6)

array([[ 0,  2,  4,  6,  8, 10]])

In [34]:
b.reshape(6,1)

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [38]:
b=np.arange(6)    #6 elements 

In [39]:
b

array([0, 1, 2, 3, 4, 5])

In [40]:
print(b)

[0 1 2 3 4 5]


In [41]:
b.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

### linspace()

In [45]:
a=np.linspace(10,100,10)

In [46]:
print(a)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [47]:
a=np.linspace(10,100,10,endpoint=False,retstep=True)

In [48]:
print(a)

(array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.]), 9.0)


In [49]:
a=np.linspace(10,100,10,endpoint=False,retstep=True,dtype=int)

In [50]:
a

(array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), 9.0)

In [51]:
print(a)

(array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), 9.0)


### logspace()

In [ ]:
a=np.logspace(1,10,10,endpoint=True)

In [64]:
print(a)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]


In [58]:
a=np.logspace(1,10,10,dtype=float)

In [59]:
print(a)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]


# Array Properties

### size()

In [70]:
a=np.arange(1,10,1)

In [74]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [80]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
np.size(a)     #size means total number of elements in an array()

9

In [93]:
a.size

9

### shape()

In [88]:
np.shape(a)      #shape means matrix of an array or dimension 

(3, 3)

In [89]:
a.shape

(3, 3)

### dtype()

In [95]:
a.dtype

dtype('int32')

# To check the dimension of an array

### np.ndim()

In [100]:
a=np.array(1)   #zero dimensional array

In [101]:
print(a.ndim)

0


In [104]:
b=np.array([1,2])   #1-dimensional array

In [103]:
print(b.ndim)

1


In [191]:
np.ndim(b)

2

# How to Change the dimensions for an array?

In [189]:
a=np.array([1,2,3,4,5,6,7,8],ndmin=2)   #converting it to 2-dimensional array

In [190]:
print(a)

[[1 2 3 4 5 6 7 8]]


# Array Operations

### Accessing and Slicing operations

In [107]:
#We can access the elements using the index method  #Indexing starts from "zero"

In [108]:
a=np.array([1,2,3,4,5,6])

In [117]:
a[0]    #accessing

1

In [118]:
a[0:]     #slicing

[1, 2, 3, 4, 5, 6]

In [120]:
a[1:3]   #excluding the index element of 3

[2, 3]

In [122]:
b=np.array([[1,2,3],[4,5,6]])

In [123]:
b.dtype

dtype('int32')

In [124]:
b.size

6

In [125]:
b.shape

(2, 3)

In [126]:
b[0]

array([1, 2, 3])

In [127]:
b[0][1]     #accessing

2

### copy()

In [137]:
a=np.array([[1,2,3],[4,5,6]])

In [149]:
b=np.copy(a)    #copying the "a" values into "b"

In [155]:
b=a.copy()

In [139]:
print(b)

[[1 2 3]
 [4 5 6]]


In [141]:
print(a)

[[1 2 3]
 [4 5 6]]


In [142]:
print(b)

[[1 2 3]
 [4 5 6]]


### view()

In [177]:
a=np.array([[1,2,3],[4,5,6]])

In [178]:
b=a.view()

In [179]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [180]:
print("a=",a)

a= [[1 2 3]
 [4 5 6]]


In [181]:
print("b=",b)

b= [[1 2 3]
 [4 5 6]]


In [182]:
a[0][1]=25

In [183]:
print(a)

[[ 1 25  3]
 [ 4  5  6]]


In [185]:
print(b)

[[ 1 25  3]
 [ 4  5  6]]


In [13]:
#note : here "a" is the refrences to "b" so what ever the changes we do to the "a" it will be also applicable to "b"

### sort()

In [14]:
a=np.array([6,5,4,3,2,1])

In [15]:
print(np.sort(a))

[1 2 3 4 5 6]


In [16]:
b=np.array([[4,3,21],[5,6,7]])

In [18]:
print(np.sort(b,axis=1))   #axis=1 means row wise operations

[[ 3  4 21]
 [ 5  6  7]]


In [19]:
print(np.sort(b,axis=0))   #axis=0 means column wise operations

[[ 4  3  7]
 [ 5  6 21]]


### another method for sorting

In [23]:
d=np.dtype([("name","S1"),("percentage","float")])     #assingning the dtype to map the values later

In [34]:
a=np.array([("ganesh",92.8),("raju",80.8),("agambaa",60.8),("jai",50.8)],dtype=d)

In [39]:
a=np.sort(a,axis=0,order="percentage")     #sorted according to the percentage

In [40]:
a

array([(b'j', 50.8), (b'a', 60.8), (b'r', 80.8), (b'g', 92.8)],
      dtype=[('name', 'S1'), ('percentage', '<f8')])

In [38]:
a.reshape(2,2)

array([[(b'j', 50.8), (b'a', 60.8)],
       [(b'r', 80.8), (b'g', 92.8)]],
      dtype=[('name', 'S1'), ('percentage', '<f8')])

### append()

In [44]:
a=np.array([10,20,30,40,50])

In [45]:
b=np.array([60,70,80,90])

In [46]:
print(np.append(a,b))

[10 20 30 40 50 60 70 80 90]


In [47]:
#Note:Even if we give a multi-dimensional array it will return a 1-dimensional array when we apply append method

In [48]:
a=np.array([[1,2,3],[4,5,6]])

In [49]:
b=np.array([[7,8,9],[10,20,30]])

In [59]:
c=np.append(a,b)

In [62]:
print(c)

[ 1  2  3  4  5  6  7  8  9 10 20 30]


### we can change the dimensions using .reshape()

In [64]:
print(c.reshape(6,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [20 30]]


### insert()

In [66]:
a=np.array([0,1,2,3,4,5,6,7,8,9])

In [71]:
a=np.insert(a,3,300)  #3= index ; 300= element to be inserted

In [75]:
print(a)

[  0   1   2 300   3   4   5   6   7   8   9]


In [74]:
np.insert(a,4,[35,36,37,38])    #to insert  multiple elements in an array

array([  0,   1,   2, 300,  35,  36,  37,  38,   3,   4,   5,   6,   7,
         8,   9])

### delete()

In [76]:
a=np.array([0,1,2,3,4,5,6])

In [77]:
a=np.delete(a,0)   #deleting the 0 index element

In [79]:
a.reshape(2,3)   #reshape

array([[1, 2, 3],
       [4, 5, 6]])

### concatenate()

In [80]:
a=np.array([[1,2,3],[4,5,6]])

In [81]:
b=np.array([[89,87,86],[23,4,5]])

In [86]:
np.concatenate((a,b))    #array in paranthesis()

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [89, 87, 86],
       [23,  4,  5]])

### stack()

In [11]:
a=np.array([[1,2,3],[4,5,6]])

In [12]:
b=np.array([[7,8,9],[10,11,12]])

In [13]:
c=np.stack((a,b))

In [14]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [15]:
c[0]    #"a"formed as an individual array 

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
c[1]    #"b" formed as an indivodual array

array([ 4,  5,  6, 10, 11, 12])

In [26]:
np.stack(c,axis=1)     #row wise operations

array([[ 1,  4],
       [ 2,  5],
       [ 3,  6],
       [ 7, 10],
       [ 8, 11],
       [ 9, 12]])

In [28]:
np.stack(c,axis=0)   #column wise operations

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### vstack() Vertical stack

In [8]:
a=np.array([[1,2,3],[4,5,6]])

In [9]:
b=np.array([[7,8,9],[10,11,12]])

In [10]:
np.vstack((a,b))    #concatenate with axis=0

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### hstack() Horizontal stack

In [1]:
import numpy as np

In [5]:
a=np.array([[1,2,3],[4,5,6]])

In [6]:
b=np.array([[7,8,9],[10,11,12]])

In [23]:
c=np.hstack((a,b))      #concatenate with axis=1

In [20]:
c[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
c[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

### dstack()

In [30]:
a=np.array([[1,2,3],[4,5,6]])

In [31]:
b=np.array([[7,8,9],[10,11,12]])

In [36]:
c=np.dstack((a,b))

In [37]:
print(c)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [38]:
c

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

### split()

In [40]:
a=np.array([1,2,3,4,5,6,7,8,9,0])

In [48]:
b=np.split(a,2)      #spliting the array in 2 equal parts

In [49]:
b

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9, 0])]

In [46]:
c=np.split(a,5)      #splitting the array in 5 equal parts

In [47]:
c

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9, 0])]

In [50]:
a1,b1,c1,d1,e1=np.split(a,5)

In [51]:
a1

array([1, 2])

In [52]:
b1

array([3, 4])

In [53]:
c1

array([5, 6])

In [54]:
d1

array([7, 8])

In [55]:
e1

array([9, 0])

### where()

In [56]:
a=np.array([1,2,3,4,5,6,7,8,9,0])

In [57]:
print(np.where(a==0))      #0 is the element placed at index=9

(array([9], dtype=int64),)


In [58]:
 b=np.array([[1,2,3],[4,5,6]])

In [59]:
print(np.where(b==6))

(array([1], dtype=int64), array([2], dtype=int64))


### searchsorted()

In [67]:
a=np.array([1,2,3])

In [70]:
a.searchsorted(1)

0

### or

In [69]:
np.searchsorted(a,1)

0

In [72]:
np.searchsorted(a,[2,3])

array([1, 2], dtype=int64)

# Arthematic Operations

### add()

In [76]:
a=np.array([1,2,3])      #adding of two 1-dimensional arrays

In [74]:
b=np.array([4,5,6])

In [75]:
np.add(a,b)

array([5, 7, 9])

### subtract()

In [84]:
a=np.array([1,2,3]) 

In [ ]:
b=np.array([4,5,6])

In [83]:
np.subtract(a,b)

array([-3, -3, -3])

### multiply()

In [85]:
a=np.array([1,2,3])

In [86]:
b=np.array([4,5,6])

In [87]:
np.multiply(a,b)

array([ 4, 10, 18])

### divide()

In [88]:
a=np.array([1,2,3])

In [89]:
b=np.array([4,5,6])

In [90]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

### exp()

In [91]:
a=np.array([1,2,3])

In [92]:
b=np.array([4,5,6])

In [94]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [95]:
np.exp(b)

array([ 54.59815003, 148.4131591 , 403.42879349])

### sqrt() squareroot

In [97]:
a=np.array([4,5,6,7,8,9])

In [98]:
b=np.array([1,2,3,4,5,6])

In [99]:
np.sqrt(a)

array([2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
       3.        ])

In [100]:
np.sqrt(b)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

# comparision

In [101]:
a=np.array([[1,2,3],[4,5,6]])

In [102]:
b=np.array([[10,20,30],[40,50,60]])

### np.array_equal(array1,array2)

In [104]:
np.array_equal(a,b)

False

In [105]:
c=np.array([1,2,3])

In [111]:
d=np.array([1,2,3])

In [112]:
a==b

array([[False, False, False],
       [False, False, False]])

In [110]:
np.array_equal(c,d)

True

In [108]:
c==d

array([ True,  True,  True])

# Array Functions

In [113]:
a=np.array([1,2,3,4,5,6,7,8,9,0])

### sum()

In [115]:
np.sum(a)

45

### min()

In [116]:
np.min(a)

0

### max()

In [117]:
np.max(a)

9

### mean()

In [118]:
np.mean(a)

4.5

### median()

In [119]:
np.median(a)

4.5

### var()

In [120]:
np.var(a)

8.25

### std()

In [121]:
np.std(a)

2.8722813232690143